packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@acdh-oeaw/eslint-config': 2.0.11
  '@acdh-oeaw/eslint-config-next': ^4.0.4
  '@acdh-oeaw/eslint-config-node': ^2.0.11
  '@acdh-oeaw/eslint-config-playwright': ^2.0.13
  '@acdh-oeaw/eslint-config-react': ^3.0.3
  '@acdh-oeaw/eslint-config-tailwindcss': ^3.0.3
  '@acdh-oeaw/lib': ^0.3.7
  '@acdh-oeaw/prettier-config': 2.0.1
  '@acdh-oeaw/tsconfig': ^1.5.1
  '@acdh-oeaw/tsconfig-lib': ^1.3.0
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@next/eslint-plugin-next': ^16.0.7
  '@playwright/test': ^1.57.0
  '@tailwindcss/postcss': ^4.1.13
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.1.9
  dotenv-cli: ^11.0.0
  eslint: 9.39.1
  eslint-config-flat-gitignore: 2.1.0
  globals: 16.5.0
  is-in-ci: ^2.0.0
  lint-staged: ^16.2.7
  next: ^16.0.7
  npm-run-all2: 8.0.4
  prettier: 3.7.4
  react: ^19.2.1
  react-dom: ^19.2.1
  simple-git-hooks: ^2.13.1
  tailwindcss: ^4.1.13
  tsdown: ^0.17.0
  tsx: ^4.21.0
  turbo: ^2.6.3
  typescript: 5.9.3
  valibot: ^1.2.0

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

shellEmulator: true

strictDepBuilds: true
